openapi: 3.0.2
info:
  description: "Central Hub for AAA (external and internal)"
  version: 1.0.0
  title: Security Module - Hestia ERP
  contact:
    email: erp.development@hestia.pt
  license:
    name: MPL-2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
externalDocs:
  description: External API Documentation available at docs.hestiaerp.com
  url: https://docs.hestiaerp.com
servers:
  - url: https://security
    description: Production Server (Runs on HTTPS Istio)
  - url: http://security-dev
    description: Development Server
  - url: http://security
    description: Local Server
tags:
  - name: internal-api
    description: Internal API related routes
  - name: example
paths:
  /internal-api/auth/{key}:
    get:
      tags:
        - internal-api
      summary: Authenticate internal api
      description: Authenticate an Internal API
      operationId: authAPI
      responses:
        "200":
          description: Returns auth key information
          content:
            application/json:
              schema:
                type: object
                required:
                  - requiredExample
                properties:
                  valid: 
                    type: boolean
                    example: true
                  api_code:
                    type: string
                    example: fiscal_documents
                  expiry_date: 
                    type: string
                    example: 2023-06-02T22:47:05Z

    #post:
    #  tags:
    #    - example
    #  summary: Creates a example
    #  description: Creates a new example
    #  operationId: createClient
    #  requestBody:
    #    content:
    #      application/json:
    #        schema:
    #          $ref: "#/components/schemas/Example"
#
    #  responses:
    #    "201":
    #      description: Example created successfully
    #    "409":
    #      description: Example already exists
    #    "422":
    #      description: Invalid example data supplied
  /asdasdas:
    get:
      tags:
        - example
      summary: Get all examples
      description: Get all examples
      operationId: getExample
      responses:
        "200":
          description: Returns all examples
    post:
      tags:
        - example
      summary: Creates a example
      description: Creates a new example
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Example"

      responses:
        "201":
          description: Example created successfully
        "409":
          description: Example already exists
        "422":
          description: Invalid example data supplied


components:
  schemas:
    Example:
      type: object
      required:
        - requiredExample
      properties:
        requiredExample: 
          type: string
          example: Example 1
        example: 
          type: string
          example: Example 2